/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nbutt' at '1/17/17 9:55 AM' with Gradle 2.14.1
 *
 * @author nbutt, @date 1/17/17 9:55 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
